/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as DemoAlgorithmIdRouteImport } from './routes/demo.$algorithmId'
import { Route as LayoutNewRouteImport } from './routes/_layout/new'
import { Route as LayoutHotRouteImport } from './routes/_layout/hot'
import { Route as LayoutExploreRouteImport } from './routes/_layout/explore'
import { Route as LayoutEventsRouteImport } from './routes/_layout/events'
import { Route as LayoutAuthRouteImport } from './routes/_layout/_auth'
import { Route as LayoutUUsernameRouteImport } from './routes/_layout/u.$username'
import { Route as LayoutEventEventIdRouteImport } from './routes/_layout/event.$eventId'
import { Route as LayoutAAlgorithmIdRouteImport } from './routes/_layout/a.$algorithmId'
import { Route as LayoutAuthProfileRouteImport } from './routes/_layout/_auth/profile'
import { Route as LayoutAuthMineRouteImport } from './routes/_layout/_auth/mine'
import { Route as LayoutAuthCreateRouteImport } from './routes/_layout/_auth/create'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const DemoAlgorithmIdRoute = DemoAlgorithmIdRouteImport.update({
  id: '/demo/$algorithmId',
  path: '/demo/$algorithmId',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutNewRoute = LayoutNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutHotRoute = LayoutHotRouteImport.update({
  id: '/hot',
  path: '/hot',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutExploreRoute = LayoutExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventsRoute = LayoutEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthRoute = LayoutAuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutUUsernameRoute = LayoutUUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutEventEventIdRoute = LayoutEventEventIdRouteImport.update({
  id: '/event/$eventId',
  path: '/event/$eventId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAAlgorithmIdRoute = LayoutAAlgorithmIdRouteImport.update({
  id: '/a/$algorithmId',
  path: '/a/$algorithmId',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAuthProfileRoute = LayoutAuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthMineRoute = LayoutAuthMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => LayoutAuthRoute,
} as any)
const LayoutAuthCreateRoute = LayoutAuthCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => LayoutAuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events': typeof LayoutEventsRoute
  '/explore': typeof LayoutExploreRoute
  '/hot': typeof LayoutHotRoute
  '/new': typeof LayoutNewRoute
  '/demo/$algorithmId': typeof DemoAlgorithmIdRoute
  '/': typeof LayoutIndexRoute
  '/create': typeof LayoutAuthCreateRoute
  '/mine': typeof LayoutAuthMineRoute
  '/profile': typeof LayoutAuthProfileRoute
  '/a/$algorithmId': typeof LayoutAAlgorithmIdRoute
  '/event/$eventId': typeof LayoutEventEventIdRoute
  '/u/$username': typeof LayoutUUsernameRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/events': typeof LayoutEventsRoute
  '/explore': typeof LayoutExploreRoute
  '/hot': typeof LayoutHotRoute
  '/new': typeof LayoutNewRoute
  '/demo/$algorithmId': typeof DemoAlgorithmIdRoute
  '/': typeof LayoutIndexRoute
  '/create': typeof LayoutAuthCreateRoute
  '/mine': typeof LayoutAuthMineRoute
  '/profile': typeof LayoutAuthProfileRoute
  '/a/$algorithmId': typeof LayoutAAlgorithmIdRoute
  '/event/$eventId': typeof LayoutEventEventIdRoute
  '/u/$username': typeof LayoutUUsernameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_layout/_auth': typeof LayoutAuthRouteWithChildren
  '/_layout/events': typeof LayoutEventsRoute
  '/_layout/explore': typeof LayoutExploreRoute
  '/_layout/hot': typeof LayoutHotRoute
  '/_layout/new': typeof LayoutNewRoute
  '/demo/$algorithmId': typeof DemoAlgorithmIdRoute
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/_auth/create': typeof LayoutAuthCreateRoute
  '/_layout/_auth/mine': typeof LayoutAuthMineRoute
  '/_layout/_auth/profile': typeof LayoutAuthProfileRoute
  '/_layout/a/$algorithmId': typeof LayoutAAlgorithmIdRoute
  '/_layout/event/$eventId': typeof LayoutEventEventIdRoute
  '/_layout/u/$username': typeof LayoutUUsernameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/signup'
    | '/events'
    | '/explore'
    | '/hot'
    | '/new'
    | '/demo/$algorithmId'
    | '/'
    | '/create'
    | '/mine'
    | '/profile'
    | '/a/$algorithmId'
    | '/event/$eventId'
    | '/u/$username'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/events'
    | '/explore'
    | '/hot'
    | '/new'
    | '/demo/$algorithmId'
    | '/'
    | '/create'
    | '/mine'
    | '/profile'
    | '/a/$algorithmId'
    | '/event/$eventId'
    | '/u/$username'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/signup'
    | '/_layout/_auth'
    | '/_layout/events'
    | '/_layout/explore'
    | '/_layout/hot'
    | '/_layout/new'
    | '/demo/$algorithmId'
    | '/_layout/'
    | '/_layout/_auth/create'
    | '/_layout/_auth/mine'
    | '/_layout/_auth/profile'
    | '/_layout/a/$algorithmId'
    | '/_layout/event/$eventId'
    | '/_layout/u/$username'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DemoAlgorithmIdRoute: typeof DemoAlgorithmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/demo/$algorithmId': {
      id: '/demo/$algorithmId'
      path: '/demo/$algorithmId'
      fullPath: '/demo/$algorithmId'
      preLoaderRoute: typeof DemoAlgorithmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/new': {
      id: '/_layout/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof LayoutNewRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/hot': {
      id: '/_layout/hot'
      path: '/hot'
      fullPath: '/hot'
      preLoaderRoute: typeof LayoutHotRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/explore': {
      id: '/_layout/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof LayoutExploreRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/events': {
      id: '/_layout/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof LayoutEventsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth': {
      id: '/_layout/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutAuthRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/u/$username': {
      id: '/_layout/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof LayoutUUsernameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/event/$eventId': {
      id: '/_layout/event/$eventId'
      path: '/event/$eventId'
      fullPath: '/event/$eventId'
      preLoaderRoute: typeof LayoutEventEventIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/a/$algorithmId': {
      id: '/_layout/a/$algorithmId'
      path: '/a/$algorithmId'
      fullPath: '/a/$algorithmId'
      preLoaderRoute: typeof LayoutAAlgorithmIdRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/_auth/profile': {
      id: '/_layout/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof LayoutAuthProfileRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/mine': {
      id: '/_layout/_auth/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof LayoutAuthMineRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
    '/_layout/_auth/create': {
      id: '/_layout/_auth/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof LayoutAuthCreateRouteImport
      parentRoute: typeof LayoutAuthRoute
    }
  }
}

interface LayoutAuthRouteChildren {
  LayoutAuthCreateRoute: typeof LayoutAuthCreateRoute
  LayoutAuthMineRoute: typeof LayoutAuthMineRoute
  LayoutAuthProfileRoute: typeof LayoutAuthProfileRoute
}

const LayoutAuthRouteChildren: LayoutAuthRouteChildren = {
  LayoutAuthCreateRoute: LayoutAuthCreateRoute,
  LayoutAuthMineRoute: LayoutAuthMineRoute,
  LayoutAuthProfileRoute: LayoutAuthProfileRoute,
}

const LayoutAuthRouteWithChildren = LayoutAuthRoute._addFileChildren(
  LayoutAuthRouteChildren,
)

interface LayoutRouteChildren {
  LayoutAuthRoute: typeof LayoutAuthRouteWithChildren
  LayoutEventsRoute: typeof LayoutEventsRoute
  LayoutExploreRoute: typeof LayoutExploreRoute
  LayoutHotRoute: typeof LayoutHotRoute
  LayoutNewRoute: typeof LayoutNewRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutAAlgorithmIdRoute: typeof LayoutAAlgorithmIdRoute
  LayoutEventEventIdRoute: typeof LayoutEventEventIdRoute
  LayoutUUsernameRoute: typeof LayoutUUsernameRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAuthRoute: LayoutAuthRouteWithChildren,
  LayoutEventsRoute: LayoutEventsRoute,
  LayoutExploreRoute: LayoutExploreRoute,
  LayoutHotRoute: LayoutHotRoute,
  LayoutNewRoute: LayoutNewRoute,
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutAAlgorithmIdRoute: LayoutAAlgorithmIdRoute,
  LayoutEventEventIdRoute: LayoutEventEventIdRoute,
  LayoutUUsernameRoute: LayoutUUsernameRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DemoAlgorithmIdRoute: DemoAlgorithmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
