/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NewRouteImport } from './routes/new'
import { Route as MineRouteImport } from './routes/mine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CreateRouteImport } from './routes/create'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AAlgorithmIdRouteImport } from './routes/a.$algorithmId'
import { Route as ApiTwitterAlgorithmIdRouteImport } from './routes/api/twitter.$algorithmId'
import { Route as ApiOgAlgorithmIdRouteImport } from './routes/api/og.$algorithmId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const MineRoute = MineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AAlgorithmIdRoute = AAlgorithmIdRouteImport.update({
  id: '/a/$algorithmId',
  path: '/a/$algorithmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwitterAlgorithmIdRoute = ApiTwitterAlgorithmIdRouteImport.update({
  id: '/api/twitter/$algorithmId',
  path: '/api/twitter/$algorithmId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOgAlgorithmIdRoute = ApiOgAlgorithmIdRouteImport.update({
  id: '/api/og/$algorithmId',
  path: '/api/og/$algorithmId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/a/$algorithmId': typeof AAlgorithmIdRoute
  '/api/og/$algorithmId': typeof ApiOgAlgorithmIdRoute
  '/api/twitter/$algorithmId': typeof ApiTwitterAlgorithmIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/a/$algorithmId': typeof AAlgorithmIdRoute
  '/api/og/$algorithmId': typeof ApiOgAlgorithmIdRoute
  '/api/twitter/$algorithmId': typeof ApiTwitterAlgorithmIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create': typeof CreateRoute
  '/login': typeof LoginRoute
  '/mine': typeof MineRoute
  '/new': typeof NewRoute
  '/profile': typeof ProfileRoute
  '/signup': typeof SignupRoute
  '/a/$algorithmId': typeof AAlgorithmIdRoute
  '/api/og/$algorithmId': typeof ApiOgAlgorithmIdRoute
  '/api/twitter/$algorithmId': typeof ApiTwitterAlgorithmIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create'
    | '/login'
    | '/mine'
    | '/new'
    | '/profile'
    | '/signup'
    | '/a/$algorithmId'
    | '/api/og/$algorithmId'
    | '/api/twitter/$algorithmId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create'
    | '/login'
    | '/mine'
    | '/new'
    | '/profile'
    | '/signup'
    | '/a/$algorithmId'
    | '/api/og/$algorithmId'
    | '/api/twitter/$algorithmId'
  id:
    | '__root__'
    | '/'
    | '/create'
    | '/login'
    | '/mine'
    | '/new'
    | '/profile'
    | '/signup'
    | '/a/$algorithmId'
    | '/api/og/$algorithmId'
    | '/api/twitter/$algorithmId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoute: typeof CreateRoute
  LoginRoute: typeof LoginRoute
  MineRoute: typeof MineRoute
  NewRoute: typeof NewRoute
  ProfileRoute: typeof ProfileRoute
  SignupRoute: typeof SignupRoute
  AAlgorithmIdRoute: typeof AAlgorithmIdRoute
  ApiOgAlgorithmIdRoute: typeof ApiOgAlgorithmIdRoute
  ApiTwitterAlgorithmIdRoute: typeof ApiTwitterAlgorithmIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mine': {
      id: '/mine'
      path: '/mine'
      fullPath: '/mine'
      preLoaderRoute: typeof MineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a/$algorithmId': {
      id: '/a/$algorithmId'
      path: '/a/$algorithmId'
      fullPath: '/a/$algorithmId'
      preLoaderRoute: typeof AAlgorithmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twitter/$algorithmId': {
      id: '/api/twitter/$algorithmId'
      path: '/api/twitter/$algorithmId'
      fullPath: '/api/twitter/$algorithmId'
      preLoaderRoute: typeof ApiTwitterAlgorithmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/og/$algorithmId': {
      id: '/api/og/$algorithmId'
      path: '/api/og/$algorithmId'
      fullPath: '/api/og/$algorithmId'
      preLoaderRoute: typeof ApiOgAlgorithmIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoute: CreateRoute,
  LoginRoute: LoginRoute,
  MineRoute: MineRoute,
  NewRoute: NewRoute,
  ProfileRoute: ProfileRoute,
  SignupRoute: SignupRoute,
  AAlgorithmIdRoute: AAlgorithmIdRoute,
  ApiOgAlgorithmIdRoute: ApiOgAlgorithmIdRoute,
  ApiTwitterAlgorithmIdRoute: ApiTwitterAlgorithmIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
