//  @ts-check

import { tanstackConfig } from '@tanstack/eslint-config'

// Find the typescript config block and modify its rules
const modifiedConfig = tanstackConfig.map((config) => {
  if (
    config.rules &&
    '@typescript-eslint/no-unnecessary-condition' in config.rules
  ) {
    return {
      ...config,
      rules: {
        ...config.rules,
        '@typescript-eslint/no-unnecessary-condition': 'warn',
        '@typescript-eslint/require-await': 'warn',
        'no-shadow': 'warn',
      },
    }
  }
  return config
})

export default [
  {
    ignores: [
      'eslint.config.js',
      'prettier.config.js',
      '.netlify', // build output
      'src/lib/database.types.ts', // auto-generated by Supabase
    ],
  },
  ...modifiedConfig,
]
